"use strict";

/**
 * Build the global sellable-weather catalog from a GeoNames cities dump.
 *
 *   1) download: https://download.geonames.org/export/dump/cities15000.zip  (unzip)
 *   2) node scripts/build-cities.js <path-to-cities15000.txt>
 *
 * Output: web/cities.js  ->  window.CITIES = [[geonameid, name, countryCode, lat, lon], ...]
 * Top 5,400 cities by population. geonameid is used as the on-chain region code.
 */

const fs = require("fs");
const path = require("path");

const LIMIT = 5400;
// Countries excluded from the sellable catalog (e.g. served via a dedicated channel).
const EXCLUDE_COUNTRIES = new Set(["KR"]);
const src = process.argv[2] || path.join(__dirname, "..", ".secrets", "tmp", "cities15000.txt");
const txt = fs.readFileSync(src, "utf8");

const rows = [];
for (const line of txt.split("\n")) {
  if (!line) continue;
  const c = line.split("\t");
  const id = Number(c[0]);
  const name = c[1];
  const lat = parseFloat(c[4]);
  const lon = parseFloat(c[5]);
  const country = c[8];
  const pop = parseInt(c[14], 10) || 0;
  if (!id || Number.isNaN(lat) || Number.isNaN(lon)) continue;
  if (EXCLUDE_COUNTRIES.has(country)) continue; // Korea excluded from the catalog
  rows.push({ id, name, country, lat, lon, pop });
}

rows.sort((a, b) => b.pop - a.pop);
const top = rows.slice(0, LIMIT);

const r4 = (x) => Math.round(x * 1e4) / 1e4;
const arr = top.map((c) => [c.id, c.name, c.country, r4(c.lat), r4(c.lon)]);

const out = `// Auto-generated by scripts/build-cities.js — top ${LIMIT} world cities by population (GeoNames, CC BY).
// [geonameid, name, countryCode, lat, lon]   (geonameid = on-chain region code)
window.CITIES = ${JSON.stringify(arr)};
`;
fs.writeFileSync(path.join(__dirname, "..", "web", "cities.js"), out);

// featured = top 12, geographically de-duplicated by country for variety
const featured = [];
const seen = new Set();
for (const c of top) {
  if (featured.length >= 12) break;
  if (seen.has(c.country)) continue;
  seen.add(c.country);
  featured.push({ id: c.id, name: c.name, country: c.country, lat: r4(c.lat), lon: r4(c.lon) });
}
fs.writeFileSync(
  path.join(__dirname, "..", "web", "featured.js"),
  `// Auto-generated — diverse default cities for the global explorer.\nwindow.FEATURED = ${JSON.stringify(featured)};\n`
);

console.log(`wrote web/cities.js (${arr.length} cities, ${(out.length / 1024).toFixed(0)} KB)`);
console.log(`featured:`, featured.map((f) => `${f.name}(${f.country})`).join(", "));
