"use strict";

/**
 * Bootstrap the base stack on BNB Smart Chain testnet: deploy KWT (ERC-20) +
 * SubscriptionManager, fund the relayer + agent wallets, pre-mint KWT, and emit a frontend
 * config (web/dapp-config.js) + deployments.<network>.json. Oracles are deployed next by
 * scripts/deploy-world-oracle.js (world) and scripts/deploy-korea.js (Korea).
 *
 *   npx hardhat run scripts/deploy-testnet.js --network baseSepolia
 */

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");
const ethers = hre.ethers;

const ONE = 10n ** 18n;

const CHAINS = {
  baseSepolia: { chainId: 84532, name: "Base Sepolia", rpc: "https://sepolia.base.org", explorer: "https://sepolia.basescan.org", currency: "ETH" },
  bscTestnet: { chainId: 97, name: "BNB Smart Chain Testnet", rpc: "https://bsc-testnet-rpc.publicnode.com", explorer: "https://testnet.bscscan.com", currency: "tBNB" },
};

function loadWallets() {
  const f = path.join(__dirname, "..", ".secrets", "wallets.json");
  return JSON.parse(fs.readFileSync(f, "utf8"));
}

async function main() {
  const net = hre.network.name;
  const wallets = loadWallets();
  const [deployer] = await ethers.getSigners();
  const relayerAddr = wallets.relayer.address;
  const agentAddr = wallets.agent.address;

  const bal = await ethers.provider.getBalance(deployer.address);
  console.log(`Network:  ${net} (chainId ${wallets.chainId})`);
  console.log(`Deployer: ${deployer.address}  balance ${ethers.formatEther(bal)} ETH`);
  if (bal === 0n) throw new Error("Deployer has 0 ETH — fund it from a faucet first.");

  // pricing
  const monthlyPrice = 100n * ONE;
  const queriesPerMonth = 1000n;
  const pricePerQuery = 1n * ONE;

  console.log("\nDeploying…");
  const token = await (await ethers.getContractFactory("MockERC20")).deploy("KWeather Token", "KWT");
  await token.waitForDeployment();
  const sm = await (await ethers.getContractFactory("SubscriptionManager")).deploy(
    await token.getAddress(), deployer.address, monthlyPrice, queriesPerMonth, pricePerQuery
  );
  await sm.waitForDeployment();
  // Oracles are deployed separately and wire SubscriptionManager.setOracle + relayer themselves:
  //   scripts/deploy-world-oracle.js (KWeatherWorldOracle) · scripts/deploy-korea.js (KWeatherKoreaOracle)

  // pre-mint KWT: agent bot + deployer (for testing)
  await (await token.mint(agentAddr, 5000n * ONE)).wait();
  await (await token.mint(deployer.address, 10000n * ONE)).wait();
  console.log("  minted KWT to agent + deployer");

  // fund relayer + agent with gas (best-effort)
  for (const [label, to, amt] of [["relayer", relayerAddr, "0.015"], ["agent", agentAddr, "0.008"]]) {
    try {
      const tx = await deployer.sendTransaction({ to, value: ethers.parseEther(amt) });
      await tx.wait();
      console.log(`  funded ${label} ${amt} ETH`);
    } catch (e) {
      console.log(`  ! could not fund ${label}: ${e.message}`);
    }
  }

  const addrs = {
    token: await token.getAddress(),
    subscriptionManager: await sm.getAddress(),
    oracle: "", // filled by scripts/deploy-world-oracle.js
  };
  const chain = CHAINS[net] || { chainId: wallets.chainId, name: net, rpc: process.env.RPC_URL || "", explorer: "", currency: "ETH" };
  const explorer = chain.explorer;
  const out = {
    network: net,
    chainId: chain.chainId,
    explorer,
    rpc: process.env.RPC_URL || chain.rpc,
    deployer: deployer.address,
    relayer: relayerAddr,
    agent: agentAddr,
    ...addrs,
    pricing: { monthlyPrice: monthlyPrice.toString(), queriesPerMonth: Number(queriesPerMonth), pricePerQuery: pricePerQuery.toString() },
  };

  fs.writeFileSync(path.join(__dirname, "..", `deployments.${net}.json`), JSON.stringify(out, null, 2));

  // frontend config (committed, public — addresses only)
  const cfg = `// Auto-generated by scripts/deploy-testnet.js — public contract addresses.
window.DAPP_CONFIG = ${JSON.stringify(
    {
      chainId: out.chainId,
      chainHex: "0x" + out.chainId.toString(16),
      chainName: chain.name,
      currency: chain.currency,
      rpc: out.rpc,
      explorer: out.explorer,
      token: out.token,
      subscriptionManager: out.subscriptionManager,
      oracle: out.oracle,
      agent: out.agent,
      pricing: out.pricing,
    },
    null,
    2
  )};
`;
  fs.writeFileSync(path.join(__dirname, "..", "web", "dapp-config.js"), cfg);

  console.log("\nDeployed (base):");
  console.log(`  KWT  ${out.token}`);
  console.log(`  SubscriptionManager  ${out.subscriptionManager}`);
  console.log(`  explorer: ${explorer}/address/${out.subscriptionManager}`);
  console.log("\nWrote deployments + web/dapp-config.js");
  console.log("Next: scripts/deploy-world-oracle.js (world) · scripts/deploy-korea.js (Korea)");
}

main().catch((e) => { console.error(e); process.exitCode = 1; });
