"use strict";

/**
 * Deploy the full oracle stack to a public testnet (Base Sepolia by default), wire it,
 * fund the relayer + agent bot wallets, pre-mint KWT to the agent, and emit a frontend
 * config (web/dapp-config.js) + deployments.<network>.json.
 *
 *   npx hardhat run scripts/deploy-testnet.js --network baseSepolia
 */

const hre = require("hardhat");
const fs = require("fs");
const path = require("path");
const ethers = hre.ethers;

const ONE = 10n ** 18n;

function loadWallets() {
  const f = path.join(__dirname, "..", ".secrets", "wallets.json");
  return JSON.parse(fs.readFileSync(f, "utf8"));
}

async function main() {
  const net = hre.network.name;
  const wallets = loadWallets();
  const [deployer] = await ethers.getSigners();
  const relayerAddr = wallets.relayer.address;
  const agentAddr = wallets.agent.address;

  const bal = await ethers.provider.getBalance(deployer.address);
  console.log(`Network:  ${net} (chainId ${wallets.chainId})`);
  console.log(`Deployer: ${deployer.address}  balance ${ethers.formatEther(bal)} ETH`);
  if (bal === 0n) throw new Error("Deployer has 0 ETH — fund it from a faucet first.");

  // pricing
  const monthlyPrice = 100n * ONE;
  const queriesPerMonth = 1000n;
  const pricePerQuery = 1n * ONE;

  console.log("\nDeploying…");
  const token = await (await ethers.getContractFactory("MockERC20")).deploy("KWeather Token", "KWT");
  await token.waitForDeployment();
  const sm = await (await ethers.getContractFactory("SubscriptionManager")).deploy(
    await token.getAddress(), deployer.address, monthlyPrice, queriesPerMonth, pricePerQuery
  );
  await sm.waitForDeployment();
  const oracle = await (await ethers.getContractFactory("KWeatherOracle")).deploy(await sm.getAddress());
  await oracle.waitForDeployment();

  await (await sm.setOracle(await oracle.getAddress())).wait();
  await (await oracle.setRelayer(relayerAddr, true)).wait();
  console.log("  wired: setOracle + setRelayer(relayer)");

  // pre-mint KWT: agent bot + deployer (for testing)
  await (await token.mint(agentAddr, 5000n * ONE)).wait();
  await (await token.mint(deployer.address, 10000n * ONE)).wait();
  console.log("  minted KWT to agent + deployer");

  // fund relayer + agent with gas (best-effort)
  for (const [label, to, amt] of [["relayer", relayerAddr, "0.015"], ["agent", agentAddr, "0.008"]]) {
    try {
      const tx = await deployer.sendTransaction({ to, value: ethers.parseEther(amt) });
      await tx.wait();
      console.log(`  funded ${label} ${amt} ETH`);
    } catch (e) {
      console.log(`  ! could not fund ${label}: ${e.message}`);
    }
  }

  const addrs = {
    token: await token.getAddress(),
    subscriptionManager: await sm.getAddress(),
    oracle: await oracle.getAddress(),
  };
  const explorer = net === "baseSepolia" ? "https://sepolia.basescan.org" : "";
  const out = {
    network: net,
    chainId: wallets.chainId,
    explorer,
    rpc: process.env.RPC_URL || "https://sepolia.base.org",
    deployer: deployer.address,
    relayer: relayerAddr,
    agent: agentAddr,
    ...addrs,
    pricing: { monthlyPrice: monthlyPrice.toString(), queriesPerMonth: Number(queriesPerMonth), pricePerQuery: pricePerQuery.toString() },
  };

  fs.writeFileSync(path.join(__dirname, "..", `deployments.${net}.json`), JSON.stringify(out, null, 2));

  // frontend config (committed, public — addresses only)
  const cfg = `// Auto-generated by scripts/deploy-testnet.js — public contract addresses.
window.DAPP_CONFIG = ${JSON.stringify(
    {
      chainId: out.chainId,
      chainHex: "0x" + out.chainId.toString(16),
      chainName: "Base Sepolia",
      rpc: out.rpc,
      explorer: out.explorer,
      token: out.token,
      subscriptionManager: out.subscriptionManager,
      oracle: out.oracle,
      agent: out.agent,
      pricing: out.pricing,
    },
    null,
    2
  )};
`;
  fs.writeFileSync(path.join(__dirname, "..", "web", "dapp-config.js"), cfg);

  console.log("\nDeployed:");
  console.log(`  KWT  ${out.token}`);
  console.log(`  SubscriptionManager  ${out.subscriptionManager}`);
  console.log(`  KWeatherOracle       ${out.oracle}`);
  console.log(`  explorer: ${explorer}/address/${out.oracle}`);
  console.log("\nWrote deployments + web/dapp-config.js");
}

main().catch((e) => { console.error(e); process.exitCode = 1; });
