// Auto-generated by scripts/deploy-testnet.js — public contract addresses.
window.DAPP_CONFIG = {
  "chainId": 97,
  "chainHex": "0x61",
  "chainName": "BNB Smart Chain Testnet",
  "currency": "tBNB",
  "rpc": "https://bsc-testnet-rpc.publicnode.com",
  "explorer": "https://testnet.bscscan.com",
  "token": "0x04090599Dbaa990eabC37fFBDE223A4eD02e5b20",
  "subscriptionManager": "0xA34D6B699f16ed574A574a3E2b18ce063da4d911",
  "oracle": "0x62FFc95E32052B7Fdd6E969fc645e3F134Fd2F3C",
  "agent": "0x7654dbB95565eb569e4a2aEBa822402338aaB67E",
  "pricing": {
    "monthlyPrice": "100000000000000000000",
    "queriesPerMonth": 1000,
    "pricePerQuery": "1000000000000000000"
  }
};
